name: Stop Actions and Run Script

on:
  push:
    branches:
      - main

jobs:
  stopactions:
    runs-on: ubuntu-latest
    steps:
      - name: Stop all running actions
        run: echo "::stop-commands::"

  runscript:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run Python script
        run: |
          python main.py $BOT_TOKEN

      - name: Clean up
        run: |
          rm -rf $BOT_TOKEN
