name: Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Previous Bot
        uses: actions/stop-previous-runs@v2
        with:
          access_token: ${{secrets.GITHUB_TOKEN}}
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Configure Environment
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run Bot
        run: |
          python main.py
