name: Stop and Run Actions on Push to main
on:
  push:
    branches:
      - main

jobs:
  stop_and_run_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Stop currently running GitHub Actions
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script with BOT_TOKEN
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
