name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          echo ${{ secrets.BOT_TOKEN }} > bot_token.txt

      - name: Check for running container
        id: check_container
        run: |
          if [ "$(docker ps -q -f name=my-python-app)" ]; then
            echo "Container is running"
          else
            echo "No running container found"
          fi

      - name: Build and run new Docker container
        if: steps.check_container.output == 'Container is running'
        run: |
          docker build -t my-python-app .
          docker stop my-python-app
          docker rm my-python-app
          docker run -d -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} --name my-python-app my-python-app
          
      - name: Build and run Docker container
        if: steps.check_container.output == 'No running container found'
        run: |
          docker build -t my-python-app .
          docker run -d -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} --name my-python-app my-python-app
