name: Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:         
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
                    
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run Bot
        run: |
          python main.py
