on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-image .

      - name: Run Docker container in the background
        run: docker run -d --restart unless-stopped --name my-container -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} my-image
